all: anchors.pdf

vc.tex: .git/logs/HEAD
	echo "%%% This file is generated by Makefile." > vc.tex
	echo "%%% Do not edit this file!\n%%%" >> vc.tex
	./date.sh >> vc.tex

anchors.pdf: anchors.tex anchors.bib textbook.sty images/*.jpg vc.tex
	pdflatex -interaction batchmode anchors.tex
	bibtex anchors.aux
	pdflatex -interaction batchmode anchors.tex
	pdflatex -interaction batchmode anchors.tex

.PHONY: clean

clean:
	rm *.bbl *.blg *.log *.out *.aux *.pdf vc.tex
